### ISSUE TITLE
Can't start this project

### ISSUE THREAD

**Issue by Hannibal2** [TernopilJS/AskApikoMobile#2]
Hello!
 I am learning react native and sometimes looking for some intersting app to learn from... 
After clone and npm install I cant run this app.
Problem  - error: 
TypeError: undefined is not a function evaluating 'navigation.getChildNavigation(route.key)'
Is thre any way to fix it?

**Comment by Hannibal2** [comment]
any updates?

**Comment by yurakruhlyk** [comment]
@Hannibal2 Hi, I think it's a problem with dependencies.
Try remove symbol ^ from version package, for example "react-navigation": "^2.0.0" -> "react-navigation": "2.0.0",

**Comment by Hannibal2** [comment]
@yurakruhlyk thanks - it helped me to solved this issue, but actually I thought this is completed app.
